name: Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
 
    - name: Build
      run: |
        go build -v .
        go vet ./...
  
    - name: Format
      uses: sjkaliski/go-github-actions/fmt@v0.5.0
      env:
        GO_IGNORE_DIRS: "./vendor"
    
    - name: Lint
      uses: sjkaliski/go-github-actions/lint@v0.5.0
      env:
        GO_LINT_PATHS: "./gandi/..."
      
    - name: TF Provider Lint
      uses: bflad/tfproviderlint-github-action@master
      with:
        args: "./..."
